#!/usr/bin/env bash

mkdir -p "$HOME/Videos"

region=$(slurp \
  -b 00000000 \
  -c ff0000ff \
  -s 00000000) || exit 0

wf-recorder \
  --audio \
  -g "$region" \
  -f "$HOME/Videos/recording_$(date +"%Y%m%d_%H%M%S").mp4"
